### ISSUE TITLE
doesn't change the time for change of workspace t

### ISSUE THREAD

**Issue by carandraug** [timbertson/gnome-shell-impatience#11]
When one changes between workspaces via keyboard Ctr+Alt+Up or Ctr+Alt+Down, this extension changes the speed of that change.  However, it doesn't change the time it takes for the layout of all workspaces to disappear from the screen afterwards.

I hope the description of the issue is clear but I can try better if it's not.

Would it be possible to add this feature?

**Comment by timbertson** [comment]
If you take a look at the source, the only thing this extension really does is:

https://github.com/timbertson/gnome-shell-impatience/blob/2880201f8f8856c1a3295c119bb74d82d6638199/impatience/extension.js#L55

So I'm afraid anything not affected by this setting is out of scope. Most likely the code you're talking about uses a timeout between two animations (show/hide), which isn't likely to be configurable from the outside, unless gnome-shell explicitly exposes it as a dconf setting somewhere.

**Comment by carandraug** [comment]
For future reference, there is another gnome-shell extension, [disable workspace switcher popup](https://extensions.gnome.org/extension/959/disable-workspace-switcher-popup/) which, together with impatience extension, effectively solved the issue.
