### ISSUE TITLE
new release/tag

### ISSUE THREAD

**Issue by carlwgeorge** [timbertson/gnome-shell-impatience#14]
The most recent tagged version only supports up to gnome shell 3.16.  The latest version of gnome shell is 3.24.

https://github.com/timbertson/gnome-shell-impatience/blob/version-0.4.3/impatience/metadata.json

Please update to be compatible with gnome shell up to version 3.24, and tag a new release with the change.

**Comment by timbertson** [comment]
I guess I've grown lazy, because almost all the changes are just metadata version bumps, and I'm uploading versions to extensions.gnome.org. Do you specifically need releases? I'd prefer people to just use the master branch, because otherwise I'd basically have to cut a release every commit.

**Comment by carlwgeorge** [comment]
Not everyone installs extensions from the website.  I'm maintaining an [AUR package](https://aur.archlinux.org/packages/gnome-shell-extension-impatience) of your extension.  It starts with [version 0.4.3](https://github.com/timbertson/gnome-shell-impatience/releases/tag/version-0.4.3), then adds 4903eaa as a patch, then finally patches the metadata to [allow shell versions up to 3.24](https://aur.archlinux.org/cgit/aur.git/tree/shell-versions.patch?h=gnome-shell-extension-impatience).  When you tag a new release I should be able to drop both patches.  Just using the master branch would not allow me to have a proper version on the package, or be notified when there are new versions, which prevents consumers of the package from getting updates for it correctly.

You don't have to releases, just git tags would be sufficient.  An approach I've seen from other extension maintainers is to just use a single digit version for simplicity ([example](https://github.com/jderose9/dash-to-panel/issues/8)).  Since your version is currently at 0.4.3, the next tag could naturally be 1, then 2, and so on.

**Comment by timbertson** [comment]
Fair enough. The tagging is not the hard part, remembering to tag is ;). I've tagged the latest master as version-0.4.4 and I'll try to remember in the future, but please feel free to open more issues or shoot me an email if I miss any.

**Comment by timbertson** [comment]
..make that 0.4.5, since I forgot to add 3.24 compat first ;)

I thought gnome shell was doing away with the strict versioning, since the API rarely changes these days.
