### ISSUE TITLE
Reduce log noise

### ISSUE THREAD

**Issue by tingvarsson** [timbertson/gnome-shell-impatience#15]
At every start of gnome shell I get:

> sep 20 12:19:05 umaro gnome-shell[1022]: [impatience] enabled
> sep 20 12:19:05 umaro gnome-shell[1022]: [impatience] enabled
> sep 20 12:19:05 umaro gnome-shell[1022]: [impatience] setting new speed: 0.75
> sep 20 12:19:05 umaro gnome-shell[1022]: [impatience] setting new speed: 0.75

Looks like very trivial logging and adds no real value. Possibly if they where hidden as debug logs somehow (not sure if there is an option like that).
Suggest cleanup and remove all logging (these two and also the one when impatience is disabled as I cant really see how that code is even triggered? Couldnt make it happen locally at least).

**Comment by timbertson** [comment]
The beauty of logging is you don't need to look at it unless something's broken, in which case it might be quite useful. The double-logging is definitely unnecessary though.

I'd consider all these logs debug logging, they're not meant for typical use. Are the logs somehow getting in your way? For me I don't see them unless I go looking in journalctl...

**Comment by tingvarsson** [comment]
You are of course not wrong, I most admit I was cleaning up my journalctl output (there was a lot of crap in there, specially after the 3.30 upgrade an a bunch of stuff broke or started throwing warning left and right :) )

But (of course there is always one of those), when actually troubleshooting some fault it helps when happy parts of the system stay as quite as possible. And rather enable extra logging in key areas than having it all on by default.

So as a general rule I rather have debug logging enabled only when needed. Of course warnings, errors, OR critical information (the tricky part to decide what is or what is not) should always be logged.

**Comment by timbertson** [comment]
Probably not, I don't see the complexity being worthwhile for such a simple
extension

**Comment by tingvarsson** [comment]
That's too bad. One could of course argue why a so simple extension even that trivial logging at all. 

Why would it not be enable for example and not have a fault visible in either the log or error logged in looking class.
Or why log exactly what the user put into the only configuration which is just propagated.

I really do dislike trivial and unnecessary logging by default. :)
