### ISSUE TITLE
not working on  19.10 / 3.34.1 gnome

### ISSUE THREAD

**Issue by paulmil1** [timbertson/gnome-shell-impatience#19]
just installed 19.10 on Gnomeshell 3.34.1
this one instantly pops up with an Error

**Comment by timbertson** [comment]
> an Error

Can you see what the error is?

**Comment by paulmil1** [comment]
sorry, it happened now its working fine after i installed it today again,
wanted to post errors back then but couldnt find any in journalctl, on the Extensions page it was just saying 'error',
since back then i installed alot of ubuntu packages, have no idea what caused it to work now,

**Comment by timbertson** [comment]
Strange (and I wish the extension page would give more detail). Well, reopen if it happens again I guess!
