### ISSUE TITLE
Request: Update for GNOME 3.36

### ISSUE THREAD

**Issue by Scotty-Trees** [timbertson/gnome-shell-impatience#20]
GNOME 3.36 is going to be released March 11 and I like your extension very much and hope it can be updated to include support for GNOME 3.36. Keep up the great work!

**Comment by timbertson** [comment]
I don't use 3.36 yet, are there some errors when running on 3.36?

**Comment by Scotty-Trees** [comment]
I use Solus GNOME 3.34 unstable edition. We'll be building 3.36 this week/next week so I can definitely test it out then and let you know!

**Comment by nnleaf** [comment]
I updated to 3.36 on Arch and it seems impatience is no longer compatible. 

I love using this tweak, so any help to get it running, I'll do it!

**Comment by ayuu5h** [comment]
it is working on gnome 3.36 fedora.

**Comment by nnleaf** [comment]
Looks like it's working for me now. Not sure what happened.

**Comment by avbor** [comment]
Does not work on Fedora 32 beta with Gnome 3.36, cant open extension settings:
![image](https://user-images.githubusercontent.com/32452033/77302720-cf176300-6d02-11ea-8a4d-fe7d717eddbb.png)
![image](https://user-images.githubusercontent.com/32452033/77302795-ef472200-6d02-11ea-990d-f9982e69dd35.png)

**Comment by avbor** [comment]
> Does not work on Fedora 32 beta with Gnome 3.36, cant open extension settings:
> ![image](https://user-images.githubusercontent.com/32452033/77302720-cf176300-6d02-11ea-8a4d-fe7d717eddbb.png)
> ![image](https://user-images.githubusercontent.com/32452033/77302795-ef472200-6d02-11ea-990d-f9982e69dd35.png)

Fixed for me by installing gnome-extensions-app =)

**Comment by derVedro** [comment]
it's working on ubuntu 20.04

**Comment by timbertson** [comment]
Nothing I can do about gnome-shell-extension-prefs being unavailable, your distro should install gnome-extensions-app if it's going to include tweak-tool :shrug: . Looks like everything else works though, so I'll close this.
