### ISSUE TITLE
small speed values and moving windows around

### ISSUE THREAD

**Issue by derVedro** [timbertson/gnome-shell-impatience#22]
I always set the speed to smallest values in the past. It was awesome. But in gnome-shell 3.36 small values cause cosmetic issues in activities overview. So if you try to drag a window, that window is rendered not under the mouse cursor.

**UPD:** It looks like a gnome shell bug

**Comment by timbertson** [comment]
Most issues in this extension are a gnome shell bug, all this actually _does_ is changing an internal setting :smiley:

**Comment by derVedro** [comment]
Yes, that is definitely a gnome shell bug. Just tested with turned off animations via gnome tweak tool. Same behavior.
