### ISSUE TITLE
Having a lower value (0.5) also affects the super key double tap speed for opening the app grid.

### ISSUE THREAD

**Issue by canbeardig** [timbertson/gnome-shell-impatience#27]
I am not sure if this is an intended feature or not but if I set the value to 0.5 I cannot double tap the super key fast enough to open the app grid. The default one and an average value like 0.75 is fine though. I am using the extension on GNOME 40.5.

**Comment by timbertson** [comment]
I'm surprised, but also there's nothing I can do - this extension is 1 line of actual code, if it has that side effect then that's how the shell works 🤷
