### ISSUE TITLE
Not working after reloading Gnome Shell (Version 45)

### ISSUE THREAD

**Issue by schnittchen** [timbertson/gnome-shell-impatience#34]
Unfortunately, Gnome Shell 45 (I'm running 45.3) has some annoying bugs which force me to reload it ("Run command", then "r"). After doing this, animation speed seems to be reset.

Disabling an d re-enabling the extension makes it work again.

I'm running this version of the extension:
```
{
  "_generated": "Generated by SweetTooth, do not edit",
  "description": "Speed up the gnome-shell animation speed",
  "name": "Impatience",
  "settings-schema": "org.gnome.shell.extensions.net.gfxmonk.impatience",
  "shell-version": [
    "45"
  ],
  "url": "http://gfxmonk.net/dist/0install/gnome-shell-impatience.xml",
  "uuid": "impatience@gfxmonk.net",
  "version": 24
}
```

BTW the version (24) does not match any repo tags...

**Comment by timbertson** [comment]
The version is autogenerated by extensions.gnome.org, it doesn't relate to my own versioning. Hoping this is fixed as of gnome 46 :crossed_fingers:
