### ISSUE TITLE
GNOME 46 Support

### ISSUE THREAD

**Issue by InklingGirl** [timbertson/gnome-shell-impatience#37]
The latest LTS version of Ubuntu is launching w/ GNOME 46 this month, so it would be great to have this extension up-to-date on https://extensions.gnome.org/extension/277/impatience/! Thank you.

**Comment by timbertson** [comment]
Done :+1: (it's in review but it's just a metadata change so it should be quick)

**Comment by InklingGirl** [comment]
Thank you very much. 🥹
